# Generated by Django 5.2.3 on 2025-07-12 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="コメント内容を入力してください",
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="コメント内容",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="有効フラグ"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                        verbose_name="ブログ記事",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                        verbose_name="親コメント",
                    ),
                ),
            ],
            options={
                "verbose_name": "コメント",
                "verbose_name_plural": "コメント",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blog_post", "-created_at"],
                        name="blog_commen_blog_po_317bbe_idx",
                    ),
                    models.Index(
                        fields=["parent", "-created_at"],
                        name="blog_commen_parent__68e95e_idx",
                    ),
                ],
            },
        ),
    ]
