# Generated by Django 5.2.3 on 2025-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_sold_out",
            field=models.BooleanField(default=False),
        ),
    ]
